server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          globalcors:
            cors-configurations:
              '[/auth/**]':
                allowedOriginPatterns:
                  - "http://localhost:5173"
                  - "http://192.168.0.104:5173"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - PATCH
                  - DELETE
                  - OPTIONS
                allowedHeaders: "*"
                allowCredentials: true
              '[/api/**]':
                allowedOriginPatterns:
                  - "http://localhost:5173"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - PATCH
                  - DELETE
                  - OPTIONS
                allowedHeaders: "*"
                allowCredentials: true
              '[/account/**]':
                allowedOriginPatterns:
                  - "http://localhost:5173"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - PATCH
                  - DELETE
                  - OPTIONS
                allowedHeaders: "*"
                allowCredentials: true

          routes:
            - id: auth-service
              uri: lb://AUTH-SERVICE
              predicates:
                - Path=/auth/**, /auth-service/v3/api-docs, /oauth2/**, /login/**, /account/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: authServiceCB
                    fallbackUri: forward:/fallback/auth

            - id: user-service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/api/profile/**, /user-service/v3/api-docs
              filters:
                - name: CircuitBreaker
                  args:
                    name: userServiceCB
                    fallbackUri: forward:/fallback/user

            - id: category-service
              uri: lb://CATEGORY-SERVICE
              predicates:
                - Path=/api/category/**, /api/option/**, /category-service/v3/api-docs, /category-service/swagger-ui/**, /api/category-set/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: categoryServiceCB
                    fallbackUri: forward:/fallback/category

            - id: room-service
              uri: lb://ROOM-SERVICE
              predicates:
                - Path=/api/room/**, /room-service/v3/api-docs
              filters:
                - name: CircuitBreaker
                  args:
                    name: roomServiceCB
                    fallbackUri: forward:/fallback/room

            - id: room-ws
              uri: lb:ws://ROOM-SERVICE
              predicates:
                - Path=/ws-room/**

            - id: decision-service
              uri: lb://DECISION-SERVICE
              predicates:
                - Path=/api/decision/**, /decision-service/v3/api-docs, /decision-service/swagger-ui/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: decisionServiceCB
                    fallbackUri: forward:/fallback/decision

            - id: decision-ws
              uri: lb:ws://DECISION-SERVICE
              predicates:
                - Path=/ws-poll/**

springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway Service
      - url: /category-service/v3/api-docs
        name: Category Service
      - url: /user-service/v3/api-docs
        name: User Service
      - url: /room-service/v3/api-docs
        name: Room Service
      - url: /auth-service/v3/api-docs
        name: Auth Service
      - url: /decision-service/v3/api-docs
        name: Decision Service

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

# Actuator Endpoints
management:
  health:
    circuit breakers:
      enabled: true

  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always

